version: '3.9'

services:
  java-build:
    build:
      context: java-build/
    volumes:
      - ./java-app-dir:/build-app-07

  java-run:
    build:
      context: java-run/
#    volumes:
 #     - java-app-dir:/run-app-07
    ports:
      - "8080:8080"
    depends_on:
      - java-build
#volumes:
#  java-app-dir: